name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GOLANG_VERSION: '1.25.0'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Set GOVERSION
        run: echo "GOVERSION=$(go version | awk '{print $3}')" >> $GITHUB_ENV

      - name: Set Gomon Version
        run: echo "GOMON_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Show version
        run: echo "GOVERSION=$GOVERSION GOMON_VERSION=$GOMON_VERSION"

      - name: Releaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOVERSION: ${{ env.GOVERSION }}
          GOMON_VERSION: ${{ env.GOMON_VERSION }}